name: Docker Image

on:
  create:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rahb-realtors-association/selenium-screenshots
  DOKKU_APP_NAME: screenshot-api
  DOKKU_REMOTE_URL: ssh://dokku@oncornerstone.app:22/screenshot-api

jobs:
  build-and-push-image:
    if: github.event.ref_type == 'tag' # This job runs only if the created object is a tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Use the Git reference (branch or tag) as the Docker tag.
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.event_name == 'push' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-dokku:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: none

    steps:
      - name: Deploy to Dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}
          git_push_flags: --force
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
